[#1] 도메인 예외 검증 추가
team-cart-king/jwp-shopping-order pull request #2
Opened 2023-05-25 03:08 UTC by swonny

### 작업 사항

## 도메인 예외

---

### CartItem

- `changeQuantity()`
    - [x]  수량이 0이하인 경우 예외를 던진다.
    - 수량이 DB 저장 가능 개수를 초과하면 예외를 던진다.

### Product

- 중복되는 이름이 존재하면 예외를 던진다.
- [x]  이름 길이가 1 이상 255 이하가 아니면 예외를 던진다.
- [x]  price가 0 이하이면 예외를 던진다.
- [x]  imageUrl에 `http://` 또는 `https://` 가 없으면 예외를 던진다.

## 요청 DTO 예외

---

### Cart API

**GET /cart-items (장바구니 아이템 조회)**

- [x]  member 정보가 잘못 입력된 경우

**POST /cart-items (장바구니 아이템 추가)**

- [x]  member 정보가 잘못 입력된 경우
- [x]  productId가 잘못 입력된 경우

**PATCH /cart-items/{id} (장바구니 아이템 수량 수정)**

- [x]  member 정보가 잘못 입력된 경우
- `CartItemQuantityUpdateRequest`
    - `requestQuantity`가
        - [x]  0 이하인 경우
        - null인 경우
            
            `int` 타입인데 `@NotNull` 어노테이션이 필요할까?
            
            ```java
            public class CartItemQuantityUpdateRequest {
            
                @NotNull(message = "수량을 입력해야 합니다.")
                @Min(value = 0, message = "수량은 음수가 될 수 없습니다.")
                private int quantity;
            
                public CartItemQuantityUpdateRequest() {
                }
            
                public CartItemQuantityUpdateRequest(int quantity) {
                    this.quantity = quantity;
                }
            
                public int getQuantity() {
                    return quantity;
                }
            }
            ```
            
        
- id가
    - [x]  null인 경우
    - [x]  `cartId` 가 잘못 입력된 경우

**DELETE /cart-items/{id}** (장바구니 아이템 삭제)

- [x]  member 정보가 잘못 입력된 경우
- id가
    - [x]  null인 경우
    - [x]  `cartId` 가 저장되어있지 않은 경우

### Product API

**GET /products/{id} (id에 해당하는 상품 목록 조회)**

- `productId` 가
    - [x]  null인 경우
    - [x]  잘못 입력된 경우

**POST /products (상품 추가)**

- [x]  `price`
- [x]  `imageUrl`
- [x]  `name`
    - 이 잘못 입력된 경우
    - null인 경우

**PUT /products/{id}** **(상품 수정)**

- [x]  member 정보가 잘못 입력된 경우
- [x]  `productId` 가 잘못 입력된 경우
- [x]  `price`
- [x]  `imageUrl`
- [x]  `name`
    - 이 잘못 입력된 경우
    - null인 경우

**DELETE /products/{id}** (상품 삭제)

- [x]  `productId` 가 null인 경우
- [ ]  `productId` 를 잘못 입력한 경우

## 전역 예외 처리

---

- [x]  DB 문제와 같은 전역 서버 문제 예외 처리 추가

### 관련 이슈

- #1

2023-05-25 06:52 UTC, hyena0608 commented on src/main/java/cart/ui/ControllerExceptionHandler.java
>  public class ControllerExceptionHandler {
`ResponseEntityExceptionHandler`를 이용해봐도 좋을거 같아 ~

2023-05-25 06:52 UTC, hyena0608 commented on src/main/java/cart/exception/ProductException.java
> +    }
이런식으로 세세하게 사용자 정의 예외를 가져가면 응답할 예외 메시지도 많이 줄어들거 같은데
`InvalidImageUrl`같은 클래스 내부에 메시지를 미리 작성해놓는거는 어떻게 생각해? 🤔 (궁금)

2023-05-25 07:41 UTC, Choi-JJunho requested changes
반영할만한 내용 위주로 리뷰남겼어! 확인 부탁해~

코멘트에 대한 컨벤션이 아직 익숙하지 않을 시점이라 접두에 붙은 알파벳의 의미는 아래 내용 참고해주면 좋을 것 같아 👍
```text
R (Request Changes) : 적극적으로 반영을 고려해주세요
C (Comment) : 웬만하면 반영해주세요
A (Approve) : 반영해도 좋고, 넘어가도 좋습니다. 사소한 의견입니다.
```

2023-05-25 07:41 UTC, Choi-JJunho commented on src/main/java/cart/dto/CartItemRequest.java
> +    @NotNull(message = "장바구니 상품 아이디를 입력해야 합니다.")
> C : `${validatedValue}`를 이용해서 사용자가 입력한 값을 알려줄 수 있어!

여기에도 적용해보면 어떨까?

```suggestion
    @NotNull(message = "장바구니 상품 아이디를 입력해야 합니다. 입력값 : ${validatedValue}")
```

2023-05-25 07:41 UTC, Choi-JJunho commented on src/main/java/cart/domain/CartItem.java
>      private final Member member;
C : 도메인에서는 Product처럼 validate 메서드를 구현해주는 편이 좋을 것 같아!

2023-05-25 07:41 UTC, Choi-JJunho commented on src/main/java/cart/domain/Member.java
>      private String password;
> C : 도메인에서는 Product처럼 validate 메서드를 구현해주는 편이 좋을 것 같아!

ditto

2023-05-25 07:41 UTC, Choi-JJunho commented on src/main/java/cart/dto/CartItemQuantityUpdateRequest.java
> +    @Min(value = 0, message = "수량은 음수가 될 수 없습니다.")
C : ${validatedValue}를 이용해서 사용자가 입력한 값을 알려줄 수 있어!
```suggestion
    @NotNull(message = "수량을 입력해야 합니다. 입력값 : ${validatedValue}")
    @Min(value = 0, message = "수량은 음수가 될 수 없습니다. 입력값 : ${validatedValue}")
```

2023-05-25 07:41 UTC, Choi-JJunho commented on src/main/java/cart/dto/ProductRequest.java
>      private int price;
R : `@Size`는 Collection의 사이즈를 의미한다고해! `@Min`, `@Max`를 사용해보면 좋을 것 같아 👍
[관련 stack overflow 링크](https://stackoverflow.com/questions/56847376/size-annotation-doesnt-seem-to-work-for-my-class)

2023-05-26 16:41 UTC, swonny commented on src/main/java/cart/ui/ControllerExceptionHandler.java
>  public class ControllerExceptionHandler {
적용해뒀어!
배워갑니다👍🏻

2023-05-26 16:46 UTC, swonny commented on src/main/java/cart/exception/ProductException.java
> +    }
같은 `InvalidImageUrl`이어도 null값이 들어올 때랑 url 포맷이 잘못된 경우로 나뉘어서 각 케이스마다 다른 예외 메시지를 던져주려고 이렇게 구현했었어!

그런데 헤나랑 주노 의견에도 동의해서 바꿔뒀어!

2023-05-26 16:47 UTC, swonny commented on src/main/java/cart/dto/CartItemRequest.java
> +    @NotNull(message = "장바구니 상품 아이디를 입력해야 합니다.")
좋은 의견 고맙습니당
반영해뒀어!

2023-05-26 16:47 UTC, swonny commented on src/main/java/cart/domain/CartItem.java
>      private final Member member;
반영해뒀어!

2023-05-26 16:47 UTC, swonny commented on src/main/java/cart/domain/Member.java
>      private String password;
이것도 반영해뒀어!

2023-05-26 16:48 UTC, swonny commented on src/main/java/cart/dto/CartItemQuantityUpdateRequest.java
> +    @Min(value = 0, message = "수량은 음수가 될 수 없습니다.")
고맙습니당 반영해뒀어!

2023-05-26 16:54 UTC, swonny commented on src/main/java/cart/dto/ProductRequest.java
>      private int price;
관련 링크 고맙습니다~
String은 `@Size` 사용했고, 나머지는 주노 코멘트처럼 `@Min`을 사용했다가 0 이하의 값에 대한 검증이어서 `@Positive`를 사용해봤어!

2023-05-27 12:52 UTC, Choi-JJunho approved these changes

2023-05-27 14:48 UTC, hyena0608 requested changes
고생했어 메리 !
조금 궁금한게 있어서 커멘트 달아봤어 😄

2023-05-27 14:48 UTC, hyena0608 commented on src/main/java/cart/domain/CartItem.java
>          this.quantity = 1;
C : Defualt 값을 상수로 주입해도 좋을거 같아
```suggestion
        this.quantity = MINIMUM_QUANTITY;
```

2023-05-27 14:48 UTC, hyena0608 commented on src/main/java/cart/domain/CartItem.java
>          this.member = member;
R : 모든 검증이 다 끝난 이후에 값을 대입하는거는 어떻게 생각해 ?
```suggestion
        validateId(id);
        validateQuantity(quantity);
        validateProduct(product);
        validateMember(member);
        this.id = id;
        this.quantity = quantity;
        this.product = product;
        this.member = member;
```

A : 검증 로직이 복잡한 경우가 아니라서 여러 메서드로 분리하지 않는게 한 눈에 보기 더 쉽다고 느껴지는데 이런거는 어때 ?

```suggestion
        validate(id, quantity, product, member);
        this.id = id;
        this.quantity = quantity;
        this.product = product;
        this.member = member;
```

2023-05-27 14:48 UTC, hyena0608 commented on src/main/java/cart/domain/Member.java
> +    private static final String EMAIL_REGEX = "^[_a-z0-9-]+(.[_a-z0-9-]+)*@(?:\\w+\\.)+\\w+$";
C : 정규표현식은 비용이 비싼다고 생각하는데 미리 Pattern 객체를 static으로 띄어놓는거는 어때 ? 🤔

2023-05-27 14:48 UTC, hyena0608 commented on src/main/java/cart/domain/Member.java
> +        }
A : 패스워드가 공백일 경우도 추가해주면 좋을거 같아 ! 여기에 공백이 들어올 일이 없다고 생각한다면 신경안써도 될 거 같아 👍

2023-05-27 14:48 UTC, hyena0608 commented on src/main/java/cart/ui/ControllerExceptionHandler.java
> +    private final Logger logger = LoggerFactory.getLogger(this.getClass().getSimpleName());
R : `ResponseEntityExceptionHandler` 내부에 이미 `Logger`가 있어서 따로 선언해줄 필요는 없을거 같아 !

2023-05-27 14:48 UTC, hyena0608 commented on src/main/java/cart/ui/ControllerExceptionHandler.java
> +        return new ResponseEntity<>(body, HttpStatus.BAD_REQUEST);
R : 다른 메서드들과 같은 형식을 유지하는게 좋을거 같아 🙂
```suggestion
        return ResponseEntity
                .status(BAD_REQUEST)
                .body(body);
```

2023-05-27 14:48 UTC, hyena0608 commented on src/main/java/cart/ui/ControllerExceptionHandler.java
>          return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
C : 내부에서 로깅하는 것도 좋지만 외부에 어떤 오류였는지 메시지 응답하는 것에 대해서는 어떻게 생각해 ? 🤔

2023-05-27 14:48 UTC, hyena0608 commented on src/test/java/cart/domain/CartItemTest.java
> +
R : 한글로 메서드 작성할 때 `_`를 지워서 가독성을 높일 수 있더라고 !

```suggestion
@DisplayNameGeneration(ReplaceUnderscores.class)
```

2023-05-29 23:01 UTC, swonny reviewed
헤나 꼼꼼하게 봐줘서 고마워~
남겨준 코멘트 반영해두었어!
테스트에 `_` 문자 제거하는 부분도 적용해뒀는데, 테스트가 깨지는 부분이 있어서 그 부분만 수정하고 다시 커밋 할게!

2023-05-29 23:01 UTC, swonny commented on src/main/java/cart/domain/CartItem.java
>          this.quantity = 1;
반영해뒀어!

2023-05-29 23:01 UTC, swonny commented on src/main/java/cart/domain/CartItem.java
>          this.member = member;
생성자가 두 개 있어서 필드 대입하기 전마다 검증하도록 했었는데
이 방식이 가독성이 더 좋은 것 같아서 변경해뒀어!

2023-05-29 23:01 UTC, swonny commented on src/main/java/cart/domain/Member.java
> +    private static final String EMAIL_REGEX = "^[_a-z0-9-]+(.[_a-z0-9-]+)*@(?:\\w+\\.)+\\w+$";
이것도 반영해뒀어! 
정규표현식이 비싼 연산이었구나!

2023-05-29 23:01 UTC, swonny commented on src/main/java/cart/ui/ControllerExceptionHandler.java
> +    private final Logger logger = LoggerFactory.getLogger(this.getClass().getSimpleName());
이것두 반영해뒀어

2023-05-29 23:01 UTC, swonny commented on src/main/java/cart/ui/ControllerExceptionHandler.java
> +        return new ResponseEntity<>(body, HttpStatus.BAD_REQUEST);
오..! 꼼꼼하게 못 봤네 🥲 반영해뒀어

2023-05-29 23:01 UTC, swonny commented on src/test/java/cart/domain/CartItemTest.java
> +
고맙습니당 반영해뒀어!

2023-05-29 23:01 UTC, swonny commented on src/main/java/cart/domain/Member.java
> +        }
패스워드나 이메일 중간에 공백이 들어올 일은 없다고 생각했는데, 앞 뒤로는 공백이 들어올 수 있을 것 같다고 생각해서

```java
    public Member(Long id, String email, String password) {
        email = email.strip();
        password = password.strip();
        validate(id, email, password);
        this.id = id;
        this.email = email;
        this.password = password;
    }
```

이렇게 유효성 검사랑 필드에 대입하기 전에 앞 뒤 공백 지울 수 있도록 변경해뒀어!
그런데 생성자에서 너무 많은 역할을 가지고 가는 것 같기도 하다는 생각이 드네..!
헤나 생각도 궁금해

2023-05-30 01:40 UTC, hyena0608 approved these changes
👍

2023-05-30 01:40 UTC, hyena0608 approved these changes
👍

2023-05-30 01:40 UTC, hyena0608 approved these changes
👍

2023-05-30 01:40 UTC, hyena0608 approved these changes
👍

2023-05-30 01:40 UTC, hyena0608 approved these changes
👍

2023-05-30 01:41 UTC, hyena0608 approved these changes
👍

2023-05-30 01:41 UTC, hyena0608 approved these changes
👍

2023-05-30 01:41 UTC, hyena0608 approved these changes
👍

2023-05-30 01:41 UTC, hyena0608 approved these changes
👍

2023-05-30 01:41 UTC, hyena0608 approved these changes
👍

2023-05-30 01:41 UTC, hyena0608 approved these changes
👍

2023-05-30 01:41 UTC, hyena0608 approved these changes
👍

2023-05-30 01:41 UTC, hyena0608 approved these changes
👍

2023-05-30 01:41 UTC, hyena0608 approved these changes
👍

2023-05-30 01:41 UTC, hyena0608 approved these changes
👍

2023-05-30 01:41 UTC, hyena0608 approved these changes
👍

2023-05-30 01:41 UTC, merged